### ISSUE TITLE
How do I get rid of the black part as a result of svs file Mask with image size (125074, 88592)?

### ISSUE THREAD

**Issue by JaeHyeok-2** [mahmoodlab/CLAM#176]
I want to make a heat map up to the masked part..
The upper right and lower left areas are masked in black as follows: I want to run `create_heatmap.py` without processing the mask, how can I solve it?

![mask](https://user-images.githubusercontent.com/89520646/218964457-88becee7-745e-4f5f-8e8e-90672cbe464e.png)
<img width="950" alt="1" src="https://user-images.githubusercontent.com/89520646/218964470-791e2028-60fc-4005-94c6-2d74bc6aba7a.png">

**Comment by Eirfaan** [comment]
I too have the same issue

**Comment by fedshyvana** [comment]
please verify that you're using pixman > 0.38 (e.g. 0.40). upgrading to pixman 0.40.0 should solve the issue - this can be done via conda.

**Comment by JaeHyeok-2** [comment]
pixman version is already 0.40 .... but the problem remains
<img width="463" alt="image" src="https://user-images.githubusercontent.com/89520646/221518650-6bada68e-428f-4ddf-9dde-8a70f3c880c0.png">
